### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by marmelin** [VSChina/vscode-ansible#257]
## Environment
- Extension version:  v0.5.2
- OS Type: Windows 10 
- VSCODE: 
```
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Datum: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Windows_NT x64 10.0.17763
```
## Summary
Installed Plugin repeatedly issues the following error:
```
[Error - 10:57:16] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 76)
[Error - 10:57:18] (node:21072) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:57:18] (node:21072) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:57:18] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
[Error - 10:57:18] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
[Error - 10:57:53] (node:21072) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:57:53] (node:21072) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:57:53] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80)
[Error - 10:57:53] (node:21072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80)
``` 

## Reproduce steps
1) Install VSCode
2) Install Ansible Plugin

**Comment by Svince123** [comment]
I have it too

**Comment by w0203j** [comment]
Same here

```[Error - 1:44:36 PM] (node:34154) UnhandledPromiseRejectionWarning: #<Object>
[Error - 1:44:36 PM] (node:34154) UnhandledPromiseRejectionWarning: #<Object>
[Error - 1:44:36 PM] (node:34154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 1:44:36 PM] (node:34154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 1:44:36 PM] (node:34154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 1:44:36 PM] (node:34154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kitos9112** [comment]
Facing the exact same issue, a very quick search via Google led me to this Github issue related to another well-known YAML LSP VSCode extension
[YAML-validation](https://github.com/redhat-developer/vscode-yaml/issues/127)

**Comment by AndrewDi** [comment]
@kitos9112 Do you mean this issue raised by another extension "YAML-validation"?

**Comment by kitos9112** [comment]
@AndrewDi - that's correct. Not quite familiar with the development of VScode extensions so cannot tell much more than my findings. I'm just wondering whether this is happening because of the use of a proxy.

**Comment by Varkal** [comment]
Same issue here on Ubuntu 19.10

**Comment by MetricMike** [comment]
vscode-ansible and vscode-yaml are both clients of yaml-language-server

Underlying issue from https://github.com/redhat-developer/vscode-yaml/issues/127 was fixed in https://github.com/redhat-developer/yaml-language-server/pull/183 and released in [0.5.8](https://github.com/redhat-developer/yaml-language-server/blob/master/CHANGELOG.md#058), but vscode-ansible [bundles version 0.4.0](https://github.com/VSChina/vscode-ansible/blob/master/server/package.json#L28).

Easing that constraint should fix, but it might be better to remove yaml validation from vscode-ansible entirely and encourage folks to use the vscode-yaml extension instead.

**Comment by Drakkai** [comment]
The problem still exists
```
[Error - 09:09:06] (node:58748) UnhandledPromiseRejectionWarning: #<Object>
[Error - 09:09:06] (node:58748) UnhandledPromiseRejectionWarning: #<Object>
[Error - 09:09:06] (node:58748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 09:09:06] (node:58748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 09:09:06] (node:58748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 09:09:06] (node:58748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
OS: Windows 10 1803
VSCode: 1.45.1
Extension: 0.5.2

**Comment by mirfire** [comment]
Happening on VSCode 1.46.1 as well.

```
[Error - 09:31:09] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 09:31:09] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 09:31:09] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 09:31:09] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 09:31:09] (node:11588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 09:31:09] (node:11588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 10:05:53] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:05:53] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 10:05:53] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 10:05:53] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 16:06:25] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 16:06:25] (node:11588) UnhandledPromiseRejectionWarning: #<Object>
[Error - 16:06:25] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[Error - 16:06:25] (node:11588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```
OS: Windows 10 1803
VSCode: 1.46.1
Extension: 0.5.2

Installed extensions:
* [DavidAnson.vscode-markdownlint@0.36.0](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
* [eamodio.gitlens@10.2.2](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
* [ms-python.python@2020.6.89148](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
* [oderwat.indent-rainbow@7.4.0](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow)
* [PKief.material-icon-theme@4.2.0](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)
* [RobbOwen.synthwave-vscode@0.1.5](https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode)
* [vscoss.vscode-ansible@0.5.2](https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible)
* [yzhang.markdown-all-in-one@3.1.0](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

**Comment by fkshom** [comment]
I worte a workaround patch based on @MetricMike 's information.
The error is no longer printed, but the extent of the impact is unknown.

https://gist.github.com/fkshom/cde7c17dc2a1352ce8676b3bb56845af

**Comment by ruruiye** [comment]
it's half years now, and this bug is still no one take fix.

**Comment by mk0a1a** [comment]
Can we get an update on this?

**Comment by jhampson-dbre** [comment]
@fkshom can you open a pull request with your patch?

On the other issue for problem the maintainer said they wouldn't have time to get to this issue soon but would take a PR.

If not, I can open one. This problem as gotten so frequent for me I've considered abandoning the extension.

https://github.com/VSChina/vscode-ansible/issues/203#issuecomment-674082495
